### ISSUE TITLE
IndexError: too many indices for array

### ISSUE THREAD

**Issue by Dicksonchin93** [anttttti/Wordbatch#24]
I developed using your code for fmftrl, received this error when running fit on it.

Traceback (most recent call last):
  File "../src/script.py", line 259, in <module>
    clf.fit(train_features, labels, 0.2, reset=False)
  File "wordbatch/models/fm_ftrl.pyx", line 227, in wordbatch.models.fm_ftrl.FM_FTRL.fit
1263.7s
18
  File "wordbatch/models/fm_ftrl.pyx", line 272, in wordbatch.models.fm_ftrl.FM_FTRL.fit_f
IndexError: too many indices for array

My train and test set shape is Shapes :  (1503424, 10016) (508438, 10016)
any idea how to solve?

**Comment by Dicksonchin93** [comment]
removed the weights and reset index from .fit function and it worked fine
